### ISSUE TITLE
i, j  and k / single letter abbrevs

### ISSUE THREAD

**Issue by philipeachille** [abbrcodes/abbreviations-in-code#14]
I noticed that in the latest version i, j  and k are missing. I think "i" is used a lot and "j" also helpful. "k" should be in the list because "v" is (as in key and value)

Possibyl it could be an idea to move all single letter abbrevs into their own section

**Comment by philipeachille** [comment]
I would not be too strict on the convention versus abbreviations matter and my vote remains to keep them in. Because as you also state, they are "short and handy" and feel a little like an abbreviation... arguably "i" could be interpreted as "item".

**Comment by T1xx1** [comment]
Got it. We can create a separate section for them or add 'i' as 'item' as you said.

**Comment by kisvegabor** [comment]
It's really hard to decide. If there aren't too many convention-like abbreviations (I can't tell more) I also suggest adding `i` and `j`.

I don't think single letter abbreviations are a special topic so I vote for adding them normally.

**Comment by kisvegabor** [comment]
![image](https://user-images.githubusercontent.com/7599318/204383881-0c81be57-4cff-4003-b54a-2fbaeec0d166.png)

It's just by accident, right?

**Comment by T1xx1** [comment]
> 
> ![image](https://user-images.githubusercontent.com/7599318/204383881-0c81be57-4cff-4003-b54a-2fbaeec0d166.png)
> 
> It's just by accident, right?

Yep, it should be - 🟢 v • value {only with **k**}

---

> It's really hard to decide. If there aren't too many convention-like abbreviations (I can't tell more) I also suggest adding i and j.

> I don't think single letter abbreviations are a special topic so I vote for adding them normally. 

I still think thay are a little different than abbreviations but ok.

**Comment by T1xx1** [comment]
![Screenshot_20221129_091428.jpg](https://user-images.githubusercontent.com/69322987/204475050-ebb83db5-b898-40a0-a1bd-2702c196457d.jpg)

If we allow conventions I have to change back this point.

**Comment by philipeachille** [comment]
... whilst you are at it, I would also suggest to change "Abbreviations in codes
The list of the abbreviations you can find and use in software environment." to "Abbreviations in code
The list of the abbreviations you can find and use in software environments."

**Comment by T1xx1** [comment]
The name of the project here on GitHub is "Abbreviations..." so to change also that?

**Comment by philipeachille** [comment]
yea, readme title = repo title. I like it's clarity

**Comment by kisvegabor** [comment]
> Yep, it should be - green_circle v • value {only with k}

fixed in 7ff206746a297fa92e7c4dadacef268ea4c4a018

> yea, readme title = repo title. I like it's clarity

fixed in bd7d9a3e5c91b48ff4c19dbb7a8c727db868ae9f

**Comment by h-h-h-h** [comment]
BTW, there are also type parameter names like `T`, `U`. Obviously, as with `i`, `j`, if you need more than one letter, by convention, you just take the next in the alphabet. So, follow-up letters have less of a right for an own entry.

**Comment by kisvegabor** [comment]
IMO 2 follow up letters can be added to show the pattern.

**Comment by philipeachille** [comment]
i agree with @h-h-h-h that "follow-up letters have less of a right for an own entry".

**Comment by T1xx1** [comment]
So, we just add "i"?

**Comment by kisvegabor** [comment]
Okay, let's add `i` only and open a new section like "Others" for `j`, `k` and similar cases.

**Comment by kisvegabor** [comment]
> Okay, let's add i only and open a new section like "Others" for j, k and similar cases.

If there is no objection, I can add the "Others" section for i, j, and k.

**Comment by T1xx1** [comment]
Nop go on after #50
