### ISSUE TITLE
Request: move project under an organization

### ISSUE THREAD

**Issue by oood** [abbrcodes/abbreviations-in-code#49]
It would be cool to have a separate name on github, and be able to add other people into the organization, making the project easier to maintain, considering that if the project wants to grow into a dictionary, then we really need more reviewers who can read and write directly to the repository.

So I propose to move this project from kisvegabor's user page to an [organization](https://github.com/account/organizations/new?plan=free).

**Things to fix:** Give the project a cool name.

An example is the [lvgl](https://github.com/lvgl) project that @kisvegabor is maintaining, it has its own organization page, and that's a really cool name.

#46 Must be resolved in advance for this issue to be considered.

**Comment by kisvegabor** [comment]
It's amazing to see that this project is growing as much that it deservs its own organization! :metal: 

I really did the same with LVGL. It stared as my hobby project but as it was growing I created an organization for it.

So, let's find a cool name! :slightly_smiling_face: 
I think something short but descriptive would be the best. E.g. `code-abbrev`. 

Ideas are very welcome! :slightly_smiling_face:

**Comment by T1xx1** [comment]
> It's amazing to see that this project is growing as much that it deservs its own organization! :metal: 
> 
> I really did the same with LVGL. It stared as my hobby project but as it was growing I created an organization for it.
> 
> So, let's find a cool name! :slightly_smiling_face: 
> I think something short but descriptive would be the best. E.g. `code-abbrev`. 
> 
> Ideas are very welcome! :slightly_smiling_face: 
> 
> 
> 

I like "abbreviations-in-code" it sounds poetic, can I suggest "Abbr in code" and maybe as short name "Aic".

**Comment by kisvegabor** [comment]
I think "Aic" is not a good a abbreviation as it's not clear immediately what it means. :smile: 

What about `shortform`?

**Comment by oood** [comment]
> and maybe as short name "Aic".

Believe me, all three word github names are no longer available.

https://github.com/oood/find-available-github-usernames

That was my first repository, and it was designed to find the shortest github username, and I did find one @l11, lol.

**Comment by oood** [comment]
> What about `shortform`?

like it, but It has been used by others since 2012 (https://github.com/shortform ). We need something special.

**Comment by oood** [comment]
> I like "abbreviations-in-code" it sounds poetic.


Yes, that is better for people to immediately realize that it is associated with the code, in fact that's how I found this project when I was looking for `database` abbreviations lol. Although I already know what the abbreviations are, I just want to double check so I don't use the wrong one.

**Comment by kisvegabor** [comment]
Finally are there any issues with keeping `abbreviations-in-code`?

**Comment by T1xx1** [comment]
> I think "Aic" is not a good a abbreviation as it's not clear immediately what it means. :smile: 

I tried 😂


> What about `shortform`?

I idk

**Comment by T1xx1** [comment]
> Finally are there any issues with keeping `abbreviations-in-code`?

No i just don't like the dashed in them.
AbbreviationsInCode camel case is the best.

**Comment by oood** [comment]
> Finally are there any issues with keeping `abbreviations-in-code`?

I don't have much of a problem with it as a repository name.

I think it's fine, it's intuitive, it doesn't create any ambiguity, but it's too verbose as an organization name.

Maybe @abbrsincode is a shorter version, for organization.

> AbbreviationsInCode camel case is the best.

Looks good, but needs to make the item easily retrievable, not sure if it's search engine friendly.


What do you guys think about this?

`programming dictionary`

**Comment by T1xx1** [comment]
The dictionary of abbrs

Lack of programming topic tho.

**Comment by T1xx1** [comment]
Let's assume we are a medium dev. The first I would search for would be "Abbreviations for codes"

**Comment by oood** [comment]
> Let's assume we are a medium dev. The first I would search for would be "Abbreviations for codes"

Yep, that's exactly what I searched for.

**Comment by T1xx1** [comment]
So I think we found our org name

**Comment by T1xx1** [comment]
Also thought that we can split the code in different repo having a Org.
Something like
- db
- website
- docs

**Comment by oood** [comment]
> "Abbreviations for codes"
> So I think we found our org name.

That's a little too long, don't you think? Usernames can be short, but Github allows a full name to be set based on the username. For example, my @l11, you can see the long name is `Libre11` after you click in.

> Also thought that we can split the code in different repo having a Org.

That would be great, and Maybe I can help maintain a color-blind user-friendly version. I do care about accessibility in my life since I have one nearly blind eye.

**Comment by T1xx1** [comment]
> > "Abbreviations for codes"
> > So I think we found our org name.
> 
> That's a little too long, don't you think? Usernames can be short, but Github allows a full name to be set based on the username. For example, my @l11, you can see the long name is `Libre11` after you click in.

We can use this as name and maybe as @ username what about "abbrcodes".


> > Also thought that we can split the code in different repo having a Org.
> 
> That would be great, and Maybe I can help maintain a color-blind user-friendly version. I do care about accessibility in my life since I have one nearly blind eye.

Really do like the idea.

**Comment by oood** [comment]
> We can use this as name and maybe as @ username what about "abbrcodes".

That's cool, I mean, really cool. It is an abbreviation itself, and it also contains `code`, so it is straight to the point, short and exquisite. I love it!


> Really do like the idea.

Yep!

**Comment by philipeachille** [comment]
How about the "Abbreviations in code committee" - AIC-Committee

Alternatively "Abbreviations in code consortium" - AIC-Consortium

**Comment by oood** [comment]
> How about the "Abbreviations in code committee" - AIC-Committee
> Alternatively "Abbreviations in code consortium" - AIC-Consortium

Sounds like the kind of organization that specifies standards lol.

**Comment by philipeachille** [comment]
> Sounds like the kind of organization that specifies standards lol.

That was the idea indeed

**Comment by oood** [comment]
> That was the idea indeed

But these abbreviations are not original to this project, it comes from a long-standing consensus. This project merely documents this consensus, so it cannot develop any standards.

**Comment by T1xx1** [comment]
> How about the "Abbreviations in code committee" - AIC-Committee

I don't likes those.
Sounds old.

> Alternatively "Abbreviations in code consortium" - AIC-Consortium


In Italy consortiums are qualified groups of people that checks food quality.
These names feel strange to me.

**Comment by philipeachille** [comment]
The suggestions were meant to be a bit of a parody on the ICANNs and W3Cs of this world, at the same time also serious. Someone should document the consensus and make it a standard to those who want that standard in their project...

**Comment by oood** [comment]
> The suggestions were meant to be a bit of a parody on the ICANNs and W3Cs of this world, at the same time also serious. Someone should document the consensus and make it a standard to those who want that standard in their project...

I think this kind of standard may stifle programming freedom, but if people are free to choose whether to follow the dictionary's advice, this dictionary can help the code readability, because most people who follow the dictionary's advice are using a way that everyone understands.

**Comment by T1xx1** [comment]
> This kind of influence usually takes years, even a decade. So isn't it a bit early to talk about this? haha

Jez you all stay calm right now we should hope that what comes out will not be a complete abomination.

**Comment by kisvegabor** [comment]
Let's proceed step by step. Turn it into an organization and if IEEE reaches out to us, we will figure out what to do :smile: 

I'd also prefer shorter names for what it's worth. `@abbrcodes` with `Abbreviations in Code` username sounds the best for me so far.

If there is a consensus, I convert this repo to an org.

**Comment by oood** [comment]
> I'd also prefer shorter names for what it's worth. @abbrcodes with Abbreviations in Code username sounds the best for me so far.

I totally agree with this.

**Comment by philipeachille** [comment]
How about @abbrorg for "The organization for Abbreviations in Code"

**Comment by T1xx1** [comment]
> How about @abbrorg for "The organization for Abbreviations in Code"

"The organization **of** Abbreviations in Code"

**Comment by philipeachille** [comment]
I believe it's "for" because the organisation serves the list. The list is "of" the organisation ("by" would be better in this case, but just to support the reasoning )

**Comment by T1xx1** [comment]
I didn't thought "Abbreviations in code" as the list's name. 
I thought the org of abbreviations in code

**Comment by T1xx1** [comment]
The discussion continues in [discussion](https://github.com/orgs/abbrcodes/discussions/4)
