### ISSUE TITLE
📖 Dictionary project (plan)

### ISSUE THREAD

**Issue by T1xx1** [abbrcodes/abbreviations-in-code#51]
I need a place to list everything we are going to do because like that I'm getting a little confused about things.

- [ ] Preparation #50
   - [x] #31 
   - [x] #32
   - [x] #33 
   - [x] #40
   - [x] #14 
   - [ ] #17 
   - [x] #19
   - [ ] #20 
   - [ ] #29
- [ ] Org
   - [ ] Confirm name and username
   - [x] Create org and add members
   - [ ] Set goals and rules. 
   - [x] #49
- [ ] Create db repo so we can leave this repo without creating a mess.
   - [x] Agree on db format [here](https://github.com/kisvegabor/abbreviations-in-code/issues/48#issuecomment-1456745206 ).
   - [x] File generator programming lang [here](https://github.com/kisvegabor/abbreviations-in-code/issues/48#issuecomment-1456749634)
   - [ ] Actually, make JSON files
- [ ] #45 
- [ ] #47 
- [ ] #48
- [ ] #46

**Comment by oood** [comment]
> I need a place to list everything we are going to do because like that I'm getting a little confused about things.

Me too, wish there was a to-do list there.

**Comment by oood** [comment]
Suggestion, we can first make it a priority to confirm the name of the org so we can create/move the repository there.

And, add you, me and other contributors to the org's membership so we have direct write access to the repository, including editing `Projects`.

**Comment by oood** [comment]
Honestly, I think our current progress is too slow.

We should `decide on the name` > `determine our goals` > `determine the database format` > and then `enter the real project development status`.

Not complaining, just that we can build the organization first, no matter what the name, because it can be changed in the future. 🙃

@kisvegabor

**Comment by T1xx1** [comment]
> Honestly, I think our current progress is too slow.

Until the org is created we cannot do much.

> 
> We should `decide on the name` > `determine our goals` > `determine the database format` > and then `enter the real project development status`.
> 

Fixing the list to keep it updated.


> Not complaining, just that we can build the organization first, no matter what the name, because it can be changed in the future. 🙃

No, I see.

 
> @kisvegabor

**Comment by kisvegabor** [comment]
Sorry for my inactivity. There are some crazy days here :slightly_smiling_face: 

I create the organization now and add you as members. We can rename it later.

**Comment by T1xx1** [comment]
Awesome

**Comment by T1xx1** [comment]
Orgs as profile has the special repo .github where we can set our rules and goals.

**Comment by kisvegabor** [comment]
I've sent "Owner" invitation for both of you.

I really have some busy days now, so it might take longer for me to reply. I'll try my best to answer, but please, do not wait for me. :slightly_smiling_face:  I don't want to block the progress. 

So now its yours too! :tada: :tada: :tada

**Comment by T1xx1** [comment]
> I've sent "Owner" invitation for both of you.

Thanks a lot😀!! I have already accepted.

> I really have some busy days now, so it might take longer for me to reply. I'll try my best to answer, but please, do not wait for me. :slightly_smiling_face:  I don't want to block the progress.

Don't worry. You're not blocking us.

> So now its yours too! :tada: :tada: :tada:

Thanks again. I promise I'll do my best to make this project fantastic 🤩.

**Comment by kisvegabor** [comment]
> Thanks again. I promise I'll do my best to make this project fantastic

I have no doubt! :relaxed:

**Comment by T1xx1** [comment]
@oood this afternoon around 5pm I can start with the tasks.

**Comment by oood** [comment]
@kisvegabor @T1xx1 
Sorry for being late everyone, I'm a little busy today and I'll try to catch up now.

> Sorry for my inactivity. There are some crazy days here 🙂

Understand, I'm going to be very busy these days too, I'm writing a new project that takes up almost all of my free time.

But don't worry, I'll allocate reasonable time for this project.

> I've sent "Owner" invitation for both of you.

Thank you.

> @oood this afternoon around 5pm I can start with the tasks.

I am coming.

**Comment by T1xx1** [comment]
There right now. I'm enabling discussion so we can chat out of issues.

**Comment by oood** [comment]
> There right now. I'm enabling discussion so we can chat out of issues.

Great!

Should we use a new repository for documenting discussions or stay in this repository?

**Comment by oood** [comment]
https://github.com/orgs/abbrcodes/projects/1/

Ok, I'm starting a project.

I picked up a random name.

Because the [dictionary](https://en.wiktionary.org/wiki/abbreviation) tells me that "abbreviation" comes from Latin ad + breviō.

**Comment by T1xx1** [comment]
> https://github.com/orgs/abbrcodes/projects/1/
> 
> Ok, I'm starting a project.

Ok
 
> I picked up a random name.
> 
> Because the [dictionary](https://en.wiktionary.org/wiki/abbreviation) tells me that "abbreviation" comes from Latin ad + breviō.

No, I like it.
Can you move in the task from this issue? I'm setting up the discussions

Discussions: https://github.com/orgs/abbrcodes/discussions

**Comment by oood** [comment]
> No, I like it.
> Can you move in the task from this issue? I'm setting up the discussions
> Discussions: https://github.com/orgs/abbrcodes/discussions

Thanks.
Great, let me see what I can do.

**Comment by T1xx1** [comment]
Moved in projects [task](https://github.com/orgs/abbrcodes/projects/1/views/2?pane=issue&itemId=22323403)

**Comment by oood** [comment]
> Moved in projects task

Good job!
